# Configuration file for Beckhoff EL1904
# Description : EtherCAT safety Terminal, slave version, 4-channel digital safety input, 24 V DC, 10 us (TBC).
vendor_id: 0x00000002
product_id: 0x07703052
rpdo: # RxPDO = receive PDO Mapping, MASTER OUT SLAVE IN
  - index: 0x1600
    channels:
      - {index: 0x7000, sub_index: 0x01, type: int8} # Command 
      - {skip: true, index: 0x0000, sub_index: 0x00, type: int8} # Gap 
      - {skip: true, index: 0x7000, sub_index: 0x02, type: int16} # CRC 0 
      - {skip: true, index: 0x7000, sub_index: 0x03, type: int16} # Connection ID 

tpdo: # TxPDO = transmit PDO Mapping, MASTER IN SLAVE OUT
  - index: 0x1a00
    channels:
      - {index: 0x6000, sub_index: 0x01, type: int8} # Command 
      - {skip: true, index: 0x6001, sub_index: 0x01, type: bit1} # Subindex 001 
      - {skip: true, index: 0x6001, sub_index: 0x02, type: bit1} # Subindex 002 
      - {skip: true, index: 0x6001, sub_index: 0x03, type: bit1} # Subindex 003 
      - {skip: true, index: 0x6001, sub_index: 0x04, type: bit1} # Subindex 004 
      - {skip: true, index: 0x0000, sub_index: 0x00, type: bit4} # Gap 
      - {skip: true, index: 0x6000, sub_index: 0x03, type: int16} # CRC0 
      - {skip: true, index: 0x6000, sub_index: 0x04, type: int16} # Connection ID       

sm: # Sync Manager
  - {index: 0, type: output, watchdog: disable }
  - {index: 1, type: input, watchdog: disable }
  - {index: 2, type: output, pdo: rpdo, watchdog: disable }
  - {index: 3, type: input, pdo: tpdo, watchdog: disable }